services:
  #tunnel:
  #  image: cloudflare/cloudflared
  #  restart: unless-stopped
  #  command: tunnel --url http://caddy:8001
  caddy:
    image: caddy:2
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - MY_DOMAIN=${MY_DOMAIN}
      - SECRET_ENDPOINT=${SECRET_ENDPOINT}
    volumes:
      - ./_data/caddy_config:/config
      - ./_data/caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./_data/public_html:/public_html
    ports:
      - "80:80"
      - "443:443"
  dlpy:
    build: dlpy
    restart: unless-stopped
    environment:
      - SECRET_ENDPOINT=${SECRET_ENDPOINT}
    volumes:
      - ./_data/public_html:/public_html
      - ./dlpy/main.py:/app/main.py
